{% set name = "HepMC3" %}
{% set version = "3.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://hepmc.web.cern.ch/hepmc/releases/{{ name }}-{{ version }}.tar.gz
  sha256: 587faa6556cc54ccd89ad35421461b4761d7809bc17a2e72f5034daea142232b
  folder: source
  patches:
    # c.f. https://gitlab.cern.ch/hepmc/HepMC3/-/merge_requests/360
    - 0001-fallback-to-readlink-if-macOS-missing-greadlink.patch  # [osx]

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - zlib
    - bzip2

test:
  source_files:
    - source/test
  requires:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  commands:

    - HepMC3-config --prefix
    - HepMC3-config --cxxflags
    - HepMC3-config --ldflags
    - HepMC3-config --libdir

    - cd source/test
    - ${CXX} -std=c++11 testMass.cc -o testMass $(HepMC3-config --cxxflags --ldflags) -Wl,-rpath,"$(HepMC3-config --libdir)"
    - ./testMass

about:
  home: https://hepmc.web.cern.ch/hepmc/
  license: GPL-3.0-or-later
  license_file: source/COPYING
  summary: HepMC3 is a new rewrite of HepMC event record.
  description: |
    HepMC3 is a new rewrite of HepMC event record. It uses shared pointers
    for in-memory navigation and the POD concept for the persistency.
  dev_url: https://gitlab.cern.ch/hepmc/HepMC3

extra:
  recipe-maintainers:
    - henryiii
    - chrisburr
    - gartung
