schema_version: 1

context:
  version: 3.3.1

package:
  name: "hepmc3"
  version: ${{ version }}

source:
  url: https://hepmc.web.cern.ch/hepmc/releases/HepMC3-${{ version }}.tar.gz
  sha256: 08240160b0f28dc3293aa4d61ce65e2d67cd597acf6faca439f2e46625f7e793
  target_directory: source
  patches:
    - 0001-Fix-cmake4-find_file.patch

build:
  number: 6
  skip: win
  dynamic_linking:
    overdepending_behavior: ignore  # Ignore until python <=3.12 is dropped
    overlinking_behavior: error

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - cmake
    - make
  host:
    - python
    - zlib
    - bzip2
    - zstd
  run:
    - python
  run_exports:
    - ${{ pin_subpackage('hepmc3', upper_bound='x.x') }}
  ignore_run_exports:
    from_package:  # cmake looks for these but doesn't use them
      - zlib
      - bzip2
      - zstd

tests:
  - files:
      source:
        - source/test
    requirements:
      run:
        - cxx-compiler
    script:
      - HepMC3-config --help
      - HepMC3-config --prefix
      - HepMC3-config --includedir
      - HepMC3-config --libdir
      - HepMC3-config --interfacesdir
      - HepMC3-config --cflags
      - HepMC3-config --cxxflags
      - HepMC3-config --ldflags

      - HepMC3-config --search
      - HepMC3-config --features
      - HepMC3-config --version

      - cd source/test
      # The v2+ versions of conda-forge compiler metapackages install minimally
      # activated compilers where the compiler toolchain works by explicit name
      # but environmental variables like CXX are no longer set.
      # c.f. https://github.com/conda-forge/conda-forge.github.io/issues/2595
      - |-
        if [[ -z "${CXX:-}" ]]; then
            if [[ "$(uname)" == "Darwin" ]]; then
                CXX="clang++"
            else
                CXX="g++"
            fi
        fi
      - "${CXX} -std=c++11 testMass.cc -o testMass $(HepMC3-config --cxxflags --ldflags) -Wl,-rpath,\"$(HepMC3-config --libdir)\""
      - ./testMass

about:
  license: GPL-3.0-or-later
  license_file: source/COPYING
  summary: HepMC3 is a new rewrite of HepMC event record.
  description: |
    HepMC3 is a new rewrite of HepMC event record. It uses shared pointers
    for in-memory navigation and the POD concept for the persistency.
  homepage: https://hepmc.web.cern.ch/hepmc/
  repository: https://gitlab.cern.ch/hepmc/HepMC3

extra:
  recipe-maintainers:
    - henryiii
    - chrisburr
    - gartung
    - matthewfeickert
    - kratsg
    - lgray
    - meiyasan
    - scarlehoff
